//
// Created by Xining Yuan on 2/24/26.
//

#ifndef QUERIES_RECEIVING_H
#define QUERIES_RECEIVING_H

#include "MultiRingORAM_Servers.h"
#include <set>
#include <map>
#include <utility>
#include <optional>

// data structures
struct txn {
    std::vector<Operat> operations;   // ── FIX (4/26/26): qualified std::
    uint32_t timestamp_id;
    bool is_committed = true;
};

// ============================================================================
// DedupPlan (4/26/26)
// ============================================================================
// Output of QueriesReceiving::Dedup().  Tells the rest of the proxy:
//   - which ops actually need to hit ORAM (oram_bound_ops)
//   - for every ORIGINAL op (keyed by global_op_id), how to resolve its
//     result (per_op_decision).
//
// Slot semantics: each Operat in oram_bound_ops occupies a slot whose
// id == its index.  Step 5 returns per_slot_results in the same order;
// per_op_decision tells the caller which slot id to pull from.
// ============================================================================

struct OpDecision {
    enum class Kind {
        TO_ORAM,              // Send to ORAM via batch; result = exec.per_slot_results[slot_id]
        BUFFERED_FROM_WRITE,  // READ resolved by an earlier same-epoch UPDATE; result = buffered_value
        COALESCED_READ,       // READ shares result with earlier same-key READ; result = exec.per_slot_results[leader_slot_id]
        DROPPED               // UPDATE superseded by later UPDATE on same key; no result
    };

    Kind kind = Kind::DROPPED;

    // For TO_ORAM: index in DedupPlan::oram_bound_ops
    uint32_t slot_id = 0;

    // For BUFFERED_FROM_WRITE: the value to return to the client (string copy
    // of the most-recent earlier UPDATE's data_value on the same key).
    std::string buffered_value;

    // For COALESCED_READ: slot_id of the leader op (a TO_ORAM read on the
    // same key earlier in this epoch).  Caller looks up
    // exec.per_slot_results[leader_slot_id] to get this op's result.
    uint32_t leader_slot_id = 0;
};

struct DedupPlan {
    // Ops to actually send to ORAM, in slot_id order (= insertion order).
    std::vector<Operat> oram_bound_ops;

    // Per-original-op resolution, keyed by Operat::global_op_id.
    // Every committed op has an entry here.  Iterate the original txns'
    // ops to look up each decision; aborted txns' ops are NOT in this map.
    std::map<uint32_t, OpDecision> per_op_decision;
};

// ============================================================================
// AssembledTxnResult (4/26/26)
// ============================================================================
// Per-txn final result, ready for delivery to the client.  Generated by
// assembleResults() which combines DedupPlan (step 3) + ExecutionResult
// (step 5) + the original txns vector (step 1/2).
//
// Caller iterates `vector<AssembledTxnResult>` and pushes each to its
// respective client connection.  How the client connection is identified
// is application-specific — keep a `txn_timestamp_id → client_fd/queue`
// map at the network layer so this struct stays lean.
// ============================================================================
struct AssembledTxnResult {
    uint32_t txn_timestamp_id = 0;
    bool     committed        = false;   // false → client should be told ABORT
    // Per-op result, in the same order as original txn.operations.
    // For READ ops on a committed txn: the decrypted plaintext (bID(4) +
    //   tuple_data + maybe trailing zero pad).  Caller may want to
    //   substr(0, 4 + tuple_width).
    // For UPDATE/INSERT ops on a committed txn: empty string ("").
    // For an aborted txn: this vector is empty (no per-op results to deliver).
    std::vector<std::string> per_op_result;
};

// ============================================================================
// assembleResults (4/26/26) — the Step-5b helper
// ============================================================================
// One-shot result aggregation.  Input:
//   - txns:     the original epoch's txn list (post-AssignAbort, so
//               t.is_committed has been set correctly)
//   - plan:     the DedupPlan from Dedup() (gives per-op decisions)
//   - er:       the ExecutionResult from executeOramOps() (gives slot results)
//
// Output: vector<AssembledTxnResult>, one entry per input txn (same order).
//
// Behavior:
//   - Aborted txns: committed=false, per_op_result empty.
//   - Committed txns: per_op_result has one entry per op:
//       * TO_ORAM    → er.per_slot_results[d.slot_id]
//       * BUFFERED   → d.buffered_value
//       * COALESCED  → er.per_slot_results[d.leader_slot_id]
//       * DROPPED    → "" (UPDATE that was superseded by later UPDATE)
//
// If er.success == false, ALL committed txns are forced to abort (caller
// can't trust partial results from a failed dispatch).
//
// IMPORTANT: this function does NOT truncate READ results to tuple_width.
// The caller knows their own schema; they should substr(0, 4 + tuple_width)
// before parsing.  We keep the raw plaintext here so the bID(4) prefix
// can be sanity-checked against the expected block_id if desired.
// ============================================================================
std::vector<AssembledTxnResult> assembleResults(
    const std::vector<txn>& txns,
    const DedupPlan&        plan,
    const struct ExecutionResult& er);

// ============================================================================
// PAPER-ALIGNED EPOCH ARCHITECTURE (4/27/26)  ────────────────────────────────
//
// This block adds the structures & APIs needed to mirror the Obladi paper's
// (R, bread, bwrite) epoch model:
//
//   Epoch i:
//     ┌─ Phase A: Read phase  ─ R sub-epochs ─────────────┐
//     │   sub-epoch 1: collect ~Δ_sub ms of ops →         │
//     │                 dedup reads against vcache →      │
//     │                 ORAM read batch of size bread →   │
//     │                 results absorbed into vcache      │
//     │   sub-epoch 2..R: same                            │
//     └────────────────────────────────────────────────────┘
//     ┌─ Phase B: Write phase ─ once ─────────────────────┐
//     │   close intake → AssignAbort over all txns →      │
//     │   dedup-to-last over UPDATE/INSERT ops →          │
//     │   ORAM write batch of size bwrite                 │
//     └────────────────────────────────────────────────────┘
//
// LEGACY (pre-4/27/26) APIs are preserved unchanged below in the class:
//   - collect_epoch / Dedup / etc.  Single-batch path.
// New code should use runEpoch_RBR_W() (free function at the bottom of this
// header).  Both paths share helpers (VCConstruct, VCAbort, executeOramOps,
// assembleResults) so they coexist safely.
// ============================================================================

struct EpochConfig {
    // Number of read sub-epochs per epoch.  For workloads w/ no dependent
    // reads, R=1 is fine (everything ends up in sub-epoch 1; sub-epochs
    // 2..R will be empty and padded out).  For TPC-C the paper uses 4-8.
    uint32_t R              = 4;

    // Per-read-batch size on the wire (fixed; under-fills are dummy-padded).
    // Obladi defaults: TPC-C ~500, FreeHealth ~200, SmallBank ~500.
    uint32_t bread          = 500;

    // Single write-batch size on the wire (one per epoch).
    // Obladi defaults: TPC-C 2000, FreeHealth 200, SmallBank ~500.
    uint32_t bwrite         = 2000;

    // Duration of each read sub-epoch's intake window (milliseconds).
    // Total epoch ≈ R × sub_epoch_ms + write phase cost.
    uint64_t sub_epoch_ms   = 25;

    // If true, every batch is exactly bread / bwrite on the wire (security
    // default per Obladi §6.2).  False = throughput-measurement mode (real
    // ops only — DO NOT use in production / paper experiments).
    bool     pad_batches    = true;
};

// ============================================================================
// VersionCache (4/27/26) — Obladi paper §6.2 "version cache"
// ============================================================================
// Per-key buffer that lives for the duration of one epoch.  Used during
// Phase A to:
//   (a) Serve dependent reads from earlier sub-epochs without going back to
//       ORAM.
//   (b) Serve reads-after-writes within the same epoch (Obladi's
//       "intermediate writes are buffered locally").
//
// Keying matches the VC keying convention: (server_id, primary_key) — same
// reason as VCConstruct (cross-partition same-PK doesn't collide).
//
// Lifecycle: created at start of an epoch, populated incrementally during
// Phase A's R sub-epochs (absorb()), consulted by dedup* calls, finally
// merged with end-of-epoch writes during Phase B.
//
// NOT thread-safe.  All accesses happen on the proxy main loop.
// ============================================================================
class VersionCache {
public:
    using Key = std::pair<int, uint32_t>;   // (server_id, primary_key)

    // Has this key been read or written so far in the current epoch?
    bool contains(const Key& k) const {
        return cache_.find(k) != cache_.end();
    }

    // Lookup; returns "" if absent.  Caller should check contains() first
    // to disambiguate "missing" from "present but empty plaintext".
    const std::string& lookup(const Key& k) const {
        auto it = cache_.find(k);
        if (it == cache_.end()) return empty_;
        return it->second;
    }

    // Manually insert (used by Phase A absorb() and by Phase B's
    // intra-epoch UPDATE buffering).
    void put(const Key& k, std::string v) {
        cache_[k] = std::move(v);
    }

    // Bulk absorb of ORAM read results from a completed read sub-epoch.
    // For each TO_ORAM read in `plan`, look up its result in `er.per_slot_results`
    // and put it into the cache keyed by (server_id, pk).
    //
    // BUFFERED_FROM_WRITE / COALESCED_READ ops are not absorbed here — the
    // dedup logic that produced them already pulled from cache, so cache
    // already has those values.
    //
    // DROPPED ops are writes (not reads); irrelevant to absorb().
    void absorb(const DedupPlan& plan, const struct ExecutionResult& er);

    // Reset for a new epoch.  Must be called between epochs.
    void clear() { cache_.clear(); }

    size_t size() const { return cache_.size(); }

private:
    std::map<Key, std::string> cache_;
    static const std::string   empty_;   // returned when lookup() misses
};

// Forward-decl of the new-style classes used by class methods below
// (so the class can reference them in signatures).
struct PhaseAReadResult;
struct PhaseBWriteResult;

class QueriesReceiving {
public:
    // ── Producer-side API (4/26/26) ──────────────────────────────────────
    // Clients call this from any thread to enqueue a txn.  Returns false
    // if the queue is between epochs (accepting flag is off); the txn is
    // dropped in that case (caller can retry next epoch).
    bool push_txn(txn t);

    std::vector<txn> collect_epoch(uint64_t interval_ms);

    // Main entry: checks completeness + builds VCs + detects MVCC conflicts
    void AssignAbort(std::vector<txn>& received_txns);

    // ── Step 3 (4/26/26): dedup-to-last + intra-epoch buffer ─────────────
    // Walks version_chain_vector_ (built by AssignAbort + VCConstruct) and
    // produces a DedupPlan.  For each key:
    //   - last UPDATE → TO_ORAM
    //   - all earlier UPDATEs on same key → DROPPED
    //   - READs after some same-epoch UPDATE → BUFFERED_FROM_WRITE
    //   - READs before any same-epoch UPDATE: first → TO_ORAM, rest → COALESCED_READ
    //
    // Must be called AFTER AssignAbort.  Aborted txns' ops are not in any
    // VC by then (VCDedup removed them), so they don't appear in the plan.
    //
    // [DEPRECATED 4/27/26 — kept for the legacy single-batch path.  New
    //  code should use the Phase-A/Phase-B pair below.]
    DedupPlan Dedup();
    // ─────────────────────────────────────────────────────────────────────

    // ════════════════════════════════════════════════════════════════════
    // PAPER-ALIGNED (R, bread, bwrite) PHASE API (4/27/26)
    // ════════════════════════════════════════════════════════════════════
    //
    // These methods replace `collect_epoch` + `Dedup` for the new design.
    // They are intended to be driven by `runEpoch_RBR_W()` (the free
    // function below this class).  Calling them directly is fine if you
    // want a custom epoch loop.
    //
    // STATE MACHINE:
    //   start_epoch()
    //   for r in 1..R:
    //     ops = collect_sub_epoch(sub_epoch_ms)
    //     plan = dedupReadsForBatch(ops, vcache)
    //     // caller dispatches `plan.oram_bound_ops` via executeOramOps
    //     vcache.absorb(plan, er)
    //   end_intake()
    //   AssignAbort(all_collected_txns_so_far)
    //   plan_w = dedupWritesAtEnd(all_committed_txns, vcache)
    //   // caller dispatches `plan_w.oram_bound_ops` via executeOramOps
    //   // call assembleResults(txns, plan_w, ew) for final output
    // ════════════════════════════════════════════════════════════════════

    // Open the intake queue for a fresh epoch.  After this returns,
    // push_txn() will accept incoming txns.  Internal counter for
    // global_op_id is reset.
    void start_epoch();

    // Block for sub_epoch_ms milliseconds, then atomically drain whatever
    // landed on the queue (without closing intake).  Returns the txns
    // received in this sub-window.  Each op gets:
    //   - txn_timestamp_id  : monotonically increasing across the whole
    //                         epoch (continues counting from the previous
    //                         sub-epoch's last id; never resets mid-epoch).
    //   - global_op_id      : monotonically increasing across the whole
    //                         epoch.
    std::vector<txn> collect_sub_epoch(uint64_t sub_epoch_ms);

    // Close the intake queue.  Subsequent push_txn() calls return false.
    // Idempotent.
    void end_intake();

    // Phase-A dedup: scan the JUST-COLLECTED sub-epoch's ops + the cache,
    // produce a DedupPlan whose oram_bound_ops contains ONLY READs that
    // need to materialize from ORAM.
    //
    // For each READ in `incoming`:
    //   - if vcache.contains((server_id, pk)) → BUFFERED_FROM_WRITE
    //     (the cache holds the most recent same-epoch value, whether from
    //      an earlier sub-epoch's ORAM read or from a same-epoch UPDATE
    //      that was already absorbed via vcache.put())
    //   - else if first sighting in this sub-epoch  → TO_ORAM (leader)
    //   - else                                       → COALESCED_READ
    //
    // UPDATE/INSERT ops in `incoming` are NOT included in the plan
    // (they're held until Phase B).  But this method DOES call
    // vcache.put() for each UPDATE/INSERT — so subsequent reads in the
    // same or later sub-epoch see their effect.  This implements
    // Obladi's "intermediate writes are buffered locally".
    //
    // NOTE: this method does NOT run AssignAbort.  Optimistic execution:
    // we serve the read from cache assuming the writer commits.  If the
    // writer aborts, MVTSO Rule A in AssignAbort (Phase B) will detect it
    // and the dependent reader is aborted too.  Cascading aborts are a
    // known cost of MVTSO (paper §6.1).
    DedupPlan dedupReadsForBatch(
        const std::vector<txn>& incoming,
        VersionCache&           vcache);

    // Phase-B dedup: scan ALL UPDATE/INSERT ops from the entire epoch
    // (across all sub-epochs) belonging to COMMITTED txns, produce a
    // DedupPlan whose oram_bound_ops contains the LAST write per key.
    //
    // Must be called AFTER AssignAbort over all_txns.  Aborted txns'
    // writes are skipped here (they were never executed against ORAM).
    //
    // Earlier writes on the same key → DROPPED.
    //
    // ─ Implementation note ─
    // Builds an internal map<(server_id,pk), last_op_pointer> walking
    // all_txns in-order; the last write wins.  The cache is not consulted
    // by this method (its job is purely to pick LAST writes), but the
    // caller can use it for sanity-checking that intermediate writes
    // have been buffered.
    DedupPlan dedupWritesAtEnd(
        const std::vector<txn>& all_txns,
        VersionCache&           vcache);
    // ════════════════════════════════════════════════════════════════════
    // ─────────────────────────────────────────────────────────────────────

    // Build version chain for one committed txn
    void VCConstruct(const txn& current_txn);

    // Scan VCs, apply MVSTO Rule A, return aborted txn timestamp_ids
    void VCAbort(std::set<uint32_t>& aborted_ids);

    // Remove aborted txns' ops from VCs
    void VCDedup(const std::set<uint32_t>& aborted_ids);

    // Clean VCs from previous epoch
    void clearVersionChains() { version_chain_vector.clear(); }

    // Accessor for testing/debugging
    const std::map<std::pair<int,uint32_t>, std::vector<Operat>>& getVersionChains() const {
        return version_chain_vector;
    }

private:
    // ── FIX (4/26/26): VC keyed by (server_id, primary_key) ──────────────
    // Was `map<uint32_t, vector<Operat>>` keyed by primary_key alone, which
    // would conflate same-PK records that landed on different partitions
    // (e.g., two different attribute bins both routed to PK=1 records on
    // server 0 vs server 3).  Now keyed by the partition assignment, so
    // VCs only collide on records that actually live on the same ORAM.
    std::map<std::pair<int,uint32_t>, std::vector<Operat>> version_chain_vector;

    // ── Phase-A internal counters (4/27/26) ──────────────────────────────
    // Cross-sub-epoch monotonic id allocators for the new (R, bread, bwrite)
    // path.  Reset by start_epoch().  Used by collect_sub_epoch() so that
    // global_op_id and txn_timestamp_id remain unique across all sub-epochs
    // of one epoch (NOT just within one sub-epoch).
    uint32_t epoch_next_ts_      = 0;
    uint32_t epoch_next_goid_    = 0;
};

// ════════════════════════════════════════════════════════════════════════════
// PAPER-ALIGNED EPOCH DRIVER (4/27/26)
// ════════════════════════════════════════════════════════════════════════════
// One-shot end-to-end runner for one (R, bread, bwrite) epoch.  Drives
// QueriesReceiving and MultiRingORAM_Servers through the full state machine.
//
// Returns AssembledTxnResult per txn that was received during this epoch
// (committed/aborted, with per-op results).  Caller is responsible for
// delivering each result to its client.
//
// THREAD SAFETY: this function blocks the calling thread for ~R × sub_epoch_ms
// + write phase time.  Producers (clients) push via push_txn() concurrently;
// the function only reads from the queue at sub-epoch boundaries (and at
// end_intake() time).
//
// Design notes:
//
// 1.  We track all txns received during ALL sub-epochs in `all_txns` so that
//     Phase B can run AssignAbort over the whole picture.  Each sub-epoch's
//     `txn` objects are kept by-value here; their internal ops carry their
//     epoch-wide global_op_id and txn_timestamp_id assigned by collect_sub_epoch.
//
// 2.  We track the `read_plans` vector across sub-epochs because Phase 5b
//     (assembleResults) needs to look up each READ op's decision.  A read
//     issued in sub-epoch 2 may have been TO_ORAM in plan[1], etc.  We
//     merge all per_op_decision maps at assembleResultsRBRW() time.
//
// 3.  ExecutionResult vectors are kept per sub-epoch.  Slot ids in plan[r]
//     index into er[r].per_slot_results — they are NOT global slot ids.
//     The combined assembler handles this correctly.
//
// 4.  If any read sub-epoch's dispatch fails (er.success == false), the
//     entire epoch is forced to abort (mirroring assembleResults's
//     fail-stop behavior, but at the epoch level — we still try to do the
//     write phase as a no-op so the proxy state stays consistent).
// ════════════════════════════════════════════════════════════════════════════

struct PhaseAReadResult {
    DedupPlan        plan;       // reads from this sub-epoch
    struct ExecutionResult er;   // ORAM results for plan.oram_bound_ops
};

struct PhaseBWriteResult {
    DedupPlan        plan;       // writes (last-update-per-key)
    struct ExecutionResult er;   // ORAM results
};

// Combine per-sub-epoch read plans + write plan + epoch's txn list into
// per-txn AssembledTxnResult.  Generalization of assembleResults() that
// can handle decisions split across multiple plans.
//
// Algorithm:
//   For each txn:
//     for each op:
//       look up op.global_op_id in:
//         (a) write_plan.per_op_decision  (UPDATE/INSERT — DROPPED or TO_ORAM)
//         (b) any read_results[r].plan.per_op_decision  (READ ops)
//       resolve to plaintext from the matching ExecutionResult.
//
// If any read_results[r].er.success == false OR write_result.er.success ==
// false, all txns are forced to abort.
std::vector<AssembledTxnResult> assembleResultsRBRW(
    const std::vector<txn>&                 txns,
    const std::vector<PhaseAReadResult>&    read_results,
    const PhaseBWriteResult&                write_result);

// One-shot epoch driver.  Returns the per-txn results in the order txns
// were received.  Internally:
//   1. qr.start_epoch()
//   2. Loop R times: collect_sub_epoch + dedupReadsForBatch +
//      mrs.executeOramOps(bread) + vcache.absorb
//   3. qr.end_intake()
//   4. qr.AssignAbort(all_txns)
//   5. qr.dedupWritesAtEnd → mrs.executeOramOps(bwrite)
//   6. assembleResultsRBRW
std::vector<AssembledTxnResult> runEpoch_RBR_W(
    QueriesReceiving&        qr,
    MultiRingORAM_Servers&   mrs,
    const EpochConfig&       cfg);

#endif //QUERIES_RECEIVING_H